export {default as Navbar} from "./Navbar/Navbar"
export {default as Header} from "./Header/Header"
export {default as About} from "./About/About"
export {default as Events} from "./Events/Events"
export {default as Timeline} from "./Timeline/Timeline"